# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=40)),
                ('avator', models.CharField(default=b'', max_length=60)),
                ('relname', models.CharField(default=b'', max_length=20)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
