# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
