# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='id_card',
            field=models.CharField(default=b'', max_length=18),
        ),
    ]
