# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='house',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
