# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimages',
            old_name='imgs',
            new_name='house',
        ),
    ]
